
package com.wushuo.p6.UserPortType;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "UserPortType", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/User/V1")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UserPortType {


    /**
     * 
     * @param user
     * @return
     *     returns java.util.List<java.lang.Integer>
     * @throws IntegrationFault
     */
    @WebMethod(operationName = "CreateUsers", action = "CreateUsers")
    @WebResult(name = "ObjectId", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/User/V1")
    @RequestWrapper(localName = "CreateUsers", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/User/V1", className = "com.wushuo.p6.UserPortType.CreateUsers")
    @ResponseWrapper(localName = "CreateUsersResponse", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/User/V1", className = "com.wushuo.p6.UserPortType.CreateUsersResponse")
    public List<Integer> createUsers(
        @WebParam(name = "User", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/User/V1")
        List<User> user)
        throws IntegrationFault
    ;

    /**
     * 
     * @param filter
     * @param field
     * @param orderBy
     * @return
     *     returns java.util.List<com.wushuo.p6.UserPortType.User>
     * @throws IntegrationFault
     */
    @WebMethod(operationName = "ReadUsers", action = "ReadUsers")
    @WebResult(name = "User", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/User/V1")
    @RequestWrapper(localName = "ReadUsers", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/User/V1", className = "com.wushuo.p6.UserPortType.ReadUsers")
    @ResponseWrapper(localName = "ReadUsersResponse", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/User/V1", className = "com.wushuo.p6.UserPortType.ReadUsersResponse")
    public List<User> readUsers(
        @WebParam(name = "Field", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/User/V1")
        List<UserFieldType> field,
        @WebParam(name = "Filter", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/User/V1")
        String filter,
        @WebParam(name = "OrderBy", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/User/V1")
        String orderBy)
        throws IntegrationFault
    ;

    /**
     * 
     * @param user
     * @return
     *     returns boolean
     * @throws IntegrationFault
     */
    @WebMethod(operationName = "UpdateUsers", action = "UpdateUsers")
    @WebResult(name = "Return", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/User/V1")
    @RequestWrapper(localName = "UpdateUsers", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/User/V1", className = "com.wushuo.p6.UserPortType.UpdateUsers")
    @ResponseWrapper(localName = "UpdateUsersResponse", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/User/V1", className = "com.wushuo.p6.UserPortType.UpdateUsersResponse")
    public boolean updateUsers(
        @WebParam(name = "User", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/User/V1")
        List<User> user)
        throws IntegrationFault
    ;

    /**
     * 
     * @param objectId
     * @return
     *     returns boolean
     * @throws IntegrationFault
     */
    @WebMethod(operationName = "DeleteUsers", action = "DeleteUsers")
    @WebResult(name = "Return", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/User/V1")
    @RequestWrapper(localName = "DeleteUsers", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/User/V1", className = "com.wushuo.p6.UserPortType.DeleteUsers")
    @ResponseWrapper(localName = "DeleteUsersResponse", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/User/V1", className = "com.wushuo.p6.UserPortType.DeleteUsersResponse")
    public boolean deleteUsers(
        @WebParam(name = "ObjectId", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/User/V1")
        List<Integer> objectId)
        throws IntegrationFault
    ;

    /**
     * 
     * @param field
     * @return
     *     returns int
     * @throws IntegrationFault
     */
    @WebMethod(action = "getFieldLengthUser")
    @WebResult(name = "Return", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/User/V1")
    @RequestWrapper(localName = "getFieldLengthUser", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/User/V1", className = "com.wushuo.p6.UserPortType.GetFieldLengthUser")
    @ResponseWrapper(localName = "getFieldLengthUserResponse", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/User/V1", className = "com.wushuo.p6.UserPortType.GetFieldLengthUserResponse")
    public int getFieldLengthUser(
        @WebParam(name = "Field", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/User/V1")
        String field)
        throws IntegrationFault
    ;

    /**
     * 
     * @param projectObjectId
     * @param tertiaryBaselineObjectId
     * @param primaryBaselineObjectId
     * @param userObjectId
     * @param secondaryBaselineObjectId
     * @throws IntegrationFault
     */
    @WebMethod(operationName = "ReadUserBaselines", action = "ReadUserBaselines")
    @RequestWrapper(localName = "ReadUserBaselines", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/User/V1", className = "com.wushuo.p6.UserPortType.ReadUserBaselines")
    @ResponseWrapper(localName = "ReadUserBaselinesResponse", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/User/V1", className = "com.wushuo.p6.UserPortType.ReadUserBaselinesResponse")
    public void readUserBaselines(
        @WebParam(name = "ProjectObjectId", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/User/V1")
        int projectObjectId,
        @WebParam(name = "UserObjectId", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/User/V1")
        int userObjectId,
        @WebParam(name = "PrimaryBaselineObjectId", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/User/V1", mode = WebParam.Mode.OUT)
        Holder<Integer> primaryBaselineObjectId,
        @WebParam(name = "SecondaryBaselineObjectId", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/User/V1", mode = WebParam.Mode.OUT)
        Holder<Integer> secondaryBaselineObjectId,
        @WebParam(name = "TertiaryBaselineObjectId", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/User/V1", mode = WebParam.Mode.OUT)
        Holder<Integer> tertiaryBaselineObjectId)
        throws IntegrationFault
    ;

    /**
     * 
     * @param projectObjectId
     * @param tertiaryBaselineObjectId
     * @param primaryBaselineObjectId
     * @param userObjectId
     * @param secondaryBaselineObjectId
     * @throws IntegrationFault
     */
    @WebMethod(operationName = "UpdateUserBaselines", action = "UpdateUserBaselines")
    @RequestWrapper(localName = "UpdateUserBaselines", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/User/V1", className = "com.wushuo.p6.UserPortType.UpdateUserBaselines")
    @ResponseWrapper(localName = "UpdateUserBaselinesResponse", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/User/V1", className = "com.wushuo.p6.UserPortType.UpdateUserBaselinesResponse")
    public void updateUserBaselines(
        @WebParam(name = "ProjectObjectId", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/User/V1")
        int projectObjectId,
        @WebParam(name = "UserObjectId", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/User/V1")
        int userObjectId,
        @WebParam(name = "PrimaryBaselineObjectId", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/User/V1", mode = WebParam.Mode.INOUT)
        Holder<Integer> primaryBaselineObjectId,
        @WebParam(name = "SecondaryBaselineObjectId", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/User/V1", mode = WebParam.Mode.INOUT)
        Holder<Integer> secondaryBaselineObjectId,
        @WebParam(name = "TertiaryBaselineObjectId", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/User/V1", mode = WebParam.Mode.INOUT)
        Holder<Integer> tertiaryBaselineObjectId)
        throws IntegrationFault
    ;

    /**
     * 
     * @param oldPassword
     * @param newPassword
     * @param userObjectId
     * @return
     *     returns boolean
     * @throws IntegrationFault
     */
    @WebMethod(operationName = "SetUserPassword", action = "SetUserPassword")
    @WebResult(name = "Success", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/User/V1")
    @RequestWrapper(localName = "SetUserPassword", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/User/V1", className = "com.wushuo.p6.UserPortType.SetUserPassword")
    @ResponseWrapper(localName = "SetUserPasswordResponse", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/User/V1", className = "com.wushuo.p6.UserPortType.SetUserPasswordResponse")
    public boolean setUserPassword(
        @WebParam(name = "UserObjectId", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/User/V1")
        int userObjectId,
        @WebParam(name = "OldPassword", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/User/V1")
        String oldPassword,
        @WebParam(name = "NewPassword", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/User/V1")
        String newPassword)
        throws IntegrationFault
    ;

    /**
     * 
     * @param newPassword
     * @param userObjectId
     * @return
     *     returns boolean
     * @throws IntegrationFault
     */
    @WebMethod(operationName = "SetMailServerPassword", action = "SetMailServerPassword")
    @WebResult(name = "Success", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/User/V1")
    @RequestWrapper(localName = "SetMailServerPassword", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/User/V1", className = "com.wushuo.p6.UserPortType.SetMailServerPassword")
    @ResponseWrapper(localName = "SetMailServerPasswordResponse", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/User/V1", className = "com.wushuo.p6.UserPortType.SetMailServerPasswordResponse")
    public boolean setMailServerPassword(
        @WebParam(name = "UserObjectId", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/User/V1")
        int userObjectId,
        @WebParam(name = "NewPassword", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/User/V1")
        String newPassword)
        throws IntegrationFault
    ;

    /**
     * 
     * @param projectObjectId
     * @param primaryBaselineObjectId
     * @param userObjectId
     * @return
     *     returns boolean
     * @throws IntegrationFault
     */
    @WebMethod(operationName = "SetPrimaryBaselineProject", action = "SetPrimaryBaselineProject")
    @WebResult(name = "Success", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/User/V1")
    @RequestWrapper(localName = "SetPrimaryBaselineProject", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/User/V1", className = "com.wushuo.p6.UserPortType.SetPrimaryBaselineProject")
    @ResponseWrapper(localName = "SetPrimaryBaselineProjectResponse", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/User/V1", className = "com.wushuo.p6.UserPortType.SetPrimaryBaselineProjectResponse")
    public boolean setPrimaryBaselineProject(
        @WebParam(name = "UserObjectId", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/User/V1")
        int userObjectId,
        @WebParam(name = "ProjectObjectId", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/User/V1")
        int projectObjectId,
        @WebParam(name = "PrimaryBaselineObjectId", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/User/V1")
        Integer primaryBaselineObjectId)
        throws IntegrationFault
    ;

    /**
     * 
     * @param projectObjectId
     * @param userObjectId
     * @return
     *     returns java.lang.Integer
     * @throws IntegrationFault
     */
    @WebMethod(operationName = "GetPrimaryBaselineProject", action = "GetPrimaryBaselineProject")
    @WebResult(name = "PrimaryBaselineObjectId", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/User/V1")
    @RequestWrapper(localName = "GetPrimaryBaselineProject", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/User/V1", className = "com.wushuo.p6.UserPortType.GetPrimaryBaselineProject")
    @ResponseWrapper(localName = "GetPrimaryBaselineProjectResponse", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/User/V1", className = "com.wushuo.p6.UserPortType.GetPrimaryBaselineProjectResponse")
    public Integer getPrimaryBaselineProject(
        @WebParam(name = "UserObjectId", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/User/V1")
        int userObjectId,
        @WebParam(name = "ProjectObjectId", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/User/V1")
        int projectObjectId)
        throws IntegrationFault
    ;

    /**
     * 
     * @param projectObjectId
     * @param userObjectId
     * @return
     *     returns java.lang.Integer
     * @throws IntegrationFault
     */
    @WebMethod(operationName = "GetSecondaryBaselineProject", action = "GetSecondaryBaselineProject")
    @WebResult(name = "SecondaryBaselineObjectId", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/User/V1")
    @RequestWrapper(localName = "GetSecondaryBaselineProject", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/User/V1", className = "com.wushuo.p6.UserPortType.GetSecondaryBaselineProject")
    @ResponseWrapper(localName = "GetSecondaryBaselineProjectResponse", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/User/V1", className = "com.wushuo.p6.UserPortType.GetSecondaryBaselineProjectResponse")
    public Integer getSecondaryBaselineProject(
        @WebParam(name = "UserObjectId", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/User/V1")
        int userObjectId,
        @WebParam(name = "ProjectObjectId", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/User/V1")
        int projectObjectId)
        throws IntegrationFault
    ;

    /**
     * 
     * @param projectObjectId
     * @param userObjectId
     * @param secondaryBaselineObjectId
     * @return
     *     returns boolean
     * @throws IntegrationFault
     */
    @WebMethod(operationName = "SetSecondaryBaselineProject", action = "SetSecondaryBaselineProject")
    @WebResult(name = "Success", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/User/V1")
    @RequestWrapper(localName = "SetSecondaryBaselineProject", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/User/V1", className = "com.wushuo.p6.UserPortType.SetSecondaryBaselineProject")
    @ResponseWrapper(localName = "SetSecondaryBaselineProjectResponse", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/User/V1", className = "com.wushuo.p6.UserPortType.SetSecondaryBaselineProjectResponse")
    public boolean setSecondaryBaselineProject(
        @WebParam(name = "UserObjectId", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/User/V1")
        int userObjectId,
        @WebParam(name = "ProjectObjectId", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/User/V1")
        int projectObjectId,
        @WebParam(name = "SecondaryBaselineObjectId", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/User/V1")
        Integer secondaryBaselineObjectId)
        throws IntegrationFault
    ;

    /**
     * 
     * @param projectObjectId
     * @param userObjectId
     * @return
     *     returns java.lang.Integer
     * @throws IntegrationFault
     */
    @WebMethod(operationName = "GetTertiaryBaselineProject", action = "GetTertiaryBaselineProject")
    @WebResult(name = "TertiaryBaselineObjectId", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/User/V1")
    @RequestWrapper(localName = "GetTertiaryBaselineProject", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/User/V1", className = "com.wushuo.p6.UserPortType.GetTertiaryBaselineProject")
    @ResponseWrapper(localName = "GetTertiaryBaselineProjectResponse", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/User/V1", className = "com.wushuo.p6.UserPortType.GetTertiaryBaselineProjectResponse")
    public Integer getTertiaryBaselineProject(
        @WebParam(name = "UserObjectId", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/User/V1")
        int userObjectId,
        @WebParam(name = "ProjectObjectId", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/User/V1")
        int projectObjectId)
        throws IntegrationFault
    ;

    /**
     * 
     * @param projectObjectId
     * @param tertiaryBaselineObjectId
     * @param userObjectId
     * @return
     *     returns boolean
     * @throws IntegrationFault
     */
    @WebMethod(operationName = "SetTertiaryBaselineProject", action = "SetTertiaryBaselineProject")
    @WebResult(name = "Success", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/User/V1")
    @RequestWrapper(localName = "SetTertiaryBaselineProject", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/User/V1", className = "com.wushuo.p6.UserPortType.SetTertiaryBaselineProject")
    @ResponseWrapper(localName = "SetTertiaryBaselineProjectResponse", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/User/V1", className = "com.wushuo.p6.UserPortType.SetTertiaryBaselineProjectResponse")
    public boolean setTertiaryBaselineProject(
        @WebParam(name = "UserObjectId", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/User/V1")
        int userObjectId,
        @WebParam(name = "ProjectObjectId", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/User/V1")
        int projectObjectId,
        @WebParam(name = "TertiaryBaselineObjectId", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/User/V1")
        Integer tertiaryBaselineObjectId)
        throws IntegrationFault
    ;

    /**
     * 
     * @param whereClause
     * @param orderBy
     * @param fields
     * @param objectId
     * @return
     *     returns java.util.List<java.lang.String>
     * @throws IntegrationFault
     */
    @WebMethod(operationName = "LoadUserFilteredMilestoneActivities", action = "LoadUserFilteredMilestoneActivities")
    @WebResult(name = "ActivityObjectIds", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/User/V1")
    @RequestWrapper(localName = "LoadUserFilteredMilestoneActivities", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/User/V1", className = "com.wushuo.p6.UserPortType.LoadUserFilteredMilestoneActivities")
    @ResponseWrapper(localName = "LoadUserFilteredMilestoneActivitiesResponse", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/User/V1", className = "com.wushuo.p6.UserPortType.LoadUserFilteredMilestoneActivitiesResponse")
    public List<String> loadUserFilteredMilestoneActivities(
        @WebParam(name = "ObjectId", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/User/V1")
        int objectId,
        @WebParam(name = "Fields", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/User/V1")
        List<String> fields,
        @WebParam(name = "WhereClause", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/User/V1")
        String whereClause,
        @WebParam(name = "OrderBy", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/User/V1")
        String orderBy)
        throws IntegrationFault
    ;

    /**
     * 
     * @param whereClause
     * @param orderBy
     * @param fields
     * @param objectId
     * @return
     *     returns java.util.List<java.lang.String>
     * @throws IntegrationFault
     */
    @WebMethod(operationName = "LoadUserFilteredActivities", action = "LoadUserFilteredActivities")
    @WebResult(name = "ActivityObjectIds", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/User/V1")
    @RequestWrapper(localName = "LoadUserFilteredActivities", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/User/V1", className = "com.wushuo.p6.UserPortType.LoadUserFilteredActivities")
    @ResponseWrapper(localName = "LoadUserFilteredActivitiesResponse", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/User/V1", className = "com.wushuo.p6.UserPortType.LoadUserFilteredActivitiesResponse")
    public List<String> loadUserFilteredActivities(
        @WebParam(name = "ObjectId", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/User/V1")
        int objectId,
        @WebParam(name = "Fields", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/User/V1")
        List<String> fields,
        @WebParam(name = "WhereClause", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/User/V1")
        String whereClause,
        @WebParam(name = "OrderBy", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/User/V1")
        String orderBy)
        throws IntegrationFault
    ;

}
