
package com.wushuo.p6.ActivityPortType;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ActivityPortType", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Activity/V1")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ActivityPortType {


    /**
     * 
     * @param activity
     * @return
     *     returns java.util.List<java.lang.Integer>
     * @throws IntegrationFault
     */
    @WebMethod(operationName = "CreateActivities", action = "CreateActivities")
    @WebResult(name = "ObjectId", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Activity/V1")
    @RequestWrapper(localName = "CreateActivities", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Activity/V1", className = "com.wushuo.p6.ActivityPortType.CreateActivities")
    @ResponseWrapper(localName = "CreateActivitiesResponse", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Activity/V1", className = "com.wushuo.p6.ActivityPortType.CreateActivitiesResponse")
    public List<Integer> createActivities(
        @WebParam(name = "Activity", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Activity/V1")
        List<Activity> activity)
        throws IntegrationFault
    ;

    /**
     * 
     * @param filter
     * @param field
     * @param orderBy
     * @return
     *     returns java.util.List<com.wushuo.p6.ActivityPortType.Activity>
     * @throws IntegrationFault
     */
    @WebMethod(operationName = "ReadActivities", action = "ReadActivities")
    @WebResult(name = "Activity", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Activity/V1")
    @RequestWrapper(localName = "ReadActivities", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Activity/V1", className = "com.wushuo.p6.ActivityPortType.ReadActivities")
    @ResponseWrapper(localName = "ReadActivitiesResponse", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Activity/V1", className = "com.wushuo.p6.ActivityPortType.ReadActivitiesResponse")
    public List<Activity> readActivities(
        @WebParam(name = "Field", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Activity/V1")
        List<ActivityFieldType> field,
        @WebParam(name = "Filter", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Activity/V1")
        String filter,
        @WebParam(name = "OrderBy", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Activity/V1")
        String orderBy)
        throws IntegrationFault
    ;

    /**
     * 
     * @param activity
     * @return
     *     returns boolean
     * @throws IntegrationFault
     */
    @WebMethod(operationName = "UpdateActivities", action = "UpdateActivities")
    @WebResult(name = "Return", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Activity/V1")
    @RequestWrapper(localName = "UpdateActivities", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Activity/V1", className = "com.wushuo.p6.ActivityPortType.UpdateActivities")
    @ResponseWrapper(localName = "UpdateActivitiesResponse", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Activity/V1", className = "com.wushuo.p6.ActivityPortType.UpdateActivitiesResponse")
    public boolean updateActivities(
        @WebParam(name = "Activity", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Activity/V1")
        List<Activity> activity)
        throws IntegrationFault
    ;

    /**
     * 
     * @param objectId
     * @return
     *     returns boolean
     * @throws IntegrationFault
     */
    @WebMethod(operationName = "DeleteActivities", action = "DeleteActivities")
    @WebResult(name = "Return", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Activity/V1")
    @RequestWrapper(localName = "DeleteActivities", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Activity/V1", className = "com.wushuo.p6.ActivityPortType.DeleteActivities")
    @ResponseWrapper(localName = "DeleteActivitiesResponse", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Activity/V1", className = "com.wushuo.p6.ActivityPortType.DeleteActivitiesResponse")
    public boolean deleteActivities(
        @WebParam(name = "ObjectId", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Activity/V1")
        List<Integer> objectId)
        throws IntegrationFault
    ;

    /**
     * 
     * @param field
     * @return
     *     returns int
     * @throws IntegrationFault
     */
    @WebMethod(action = "getFieldLengthActivity")
    @WebResult(name = "Return", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Activity/V1")
    @RequestWrapper(localName = "getFieldLengthActivity", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Activity/V1", className = "com.wushuo.p6.ActivityPortType.GetFieldLengthActivity")
    @ResponseWrapper(localName = "getFieldLengthActivityResponse", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Activity/V1", className = "com.wushuo.p6.ActivityPortType.GetFieldLengthActivityResponse")
    public int getFieldLengthActivity(
        @WebParam(name = "Field", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Activity/V1")
        String field)
        throws IntegrationFault
    ;

    /**
     * 
     * @param targetActivityId
     * @param copyActivityCodes
     * @param copyProjectDocuments
     * @param copyActivityNotes
     * @param targetProjectObjectId
     * @param copyResourceAndRoleAssignments
     * @param copyActivitySteps
     * @param copyPastPeriodActuals
     * @param targetWBSObjectId
     * @param copyRelationships
     * @param objectId
     * @param copyActivityExpenses
     * @throws IntegrationFault
     */
    @WebMethod(operationName = "CopyActivity", action = "CopyActivity")
    @RequestWrapper(localName = "CopyActivity", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Activity/V1", className = "com.wushuo.p6.ActivityPortType.CopyActivity")
    @ResponseWrapper(localName = "CopyActivityResponse", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Activity/V1", className = "com.wushuo.p6.ActivityPortType.CopyActivityResponse")
    public void copyActivity(
        @WebParam(name = "ObjectId", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Activity/V1", mode = WebParam.Mode.INOUT)
        Holder<Integer> objectId,
        @WebParam(name = "TargetProjectObjectId", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Activity/V1")
        Integer targetProjectObjectId,
        @WebParam(name = "TargetWBSObjectId", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Activity/V1")
        Integer targetWBSObjectId,
        @WebParam(name = "TargetActivityId", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Activity/V1")
        String targetActivityId,
        @WebParam(name = "CopyResourceAndRoleAssignments", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Activity/V1")
        Boolean copyResourceAndRoleAssignments,
        @WebParam(name = "CopyRelationships", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Activity/V1")
        Boolean copyRelationships,
        @WebParam(name = "CopyActivityCodes", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Activity/V1")
        Boolean copyActivityCodes,
        @WebParam(name = "CopyActivityNotes", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Activity/V1")
        Boolean copyActivityNotes,
        @WebParam(name = "CopyActivityExpenses", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Activity/V1")
        Boolean copyActivityExpenses,
        @WebParam(name = "CopyActivitySteps", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Activity/V1")
        Boolean copyActivitySteps,
        @WebParam(name = "CopyProjectDocuments", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Activity/V1")
        Boolean copyProjectDocuments,
        @WebParam(name = "CopyPastPeriodActuals", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Activity/V1")
        Boolean copyPastPeriodActuals)
        throws IntegrationFault
    ;

    /**
     * 
     * @param filter
     * @param field
     * @param orderBy
     * @param wbsObjectId
     * @return
     *     returns java.util.List<com.wushuo.p6.ActivityPortType.Activity>
     * @throws IntegrationFault
     */
    @WebMethod(operationName = "ReadAllActivitiesByWBS", action = "ReadAllActivitiesByWBS")
    @WebResult(name = "Activity", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Activity/V1")
    @RequestWrapper(localName = "ReadAllActivitiesByWBS", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Activity/V1", className = "com.wushuo.p6.ActivityPortType.ReadAllActivitiesByWBS")
    @ResponseWrapper(localName = "ReadAllActivitiesByWBSResponse", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Activity/V1", className = "com.wushuo.p6.ActivityPortType.ReadAllActivitiesByWBSResponse")
    public List<Activity> readAllActivitiesByWBS(
        @WebParam(name = "WBSObjectId", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Activity/V1")
        int wbsObjectId,
        @WebParam(name = "Field", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Activity/V1")
        List<ActivityFieldType> field,
        @WebParam(name = "Filter", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Activity/V1")
        String filter,
        @WebParam(name = "OrderBy", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Activity/V1")
        String orderBy)
        throws IntegrationFault
    ;

    /**
     * 
     * @param objectId
     * @return
     *     returns boolean
     * @throws IntegrationFault
     */
    @WebMethod(operationName = "DissolveActivity", action = "DissolveActivity")
    @WebResult(name = "Return", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Activity/V1")
    @RequestWrapper(localName = "DissolveActivity", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Activity/V1", className = "com.wushuo.p6.ActivityPortType.DissolveActivity")
    @ResponseWrapper(localName = "DissolveActivityResponse", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Activity/V1", className = "com.wushuo.p6.ActivityPortType.DissolveActivityResponse")
    public boolean dissolveActivity(
        @WebParam(name = "ObjectId", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Activity/V1")
        int objectId)
        throws IntegrationFault
    ;

}
