
package com.wushuo.p6.ActivityPortType;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ActivityService", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Activity/V1", wsdlLocation = "http://192.168.14.217:8206/p6ws/services/ActivityService?wsdl")
public class ActivityService
    extends Service
{

    private final static URL ACTIVITYSERVICE_WSDL_LOCATION;
    private final static WebServiceException ACTIVITYSERVICE_EXCEPTION;
    private final static QName ACTIVITYSERVICE_QNAME = new QName("http://xmlns.oracle.com/Primavera/P6/WS/Activity/V1", "ActivityService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.14.217:8206/p6ws/services/ActivityService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ACTIVITYSERVICE_WSDL_LOCATION = url;
        ACTIVITYSERVICE_EXCEPTION = e;
    }

    public ActivityService() {
        super(__getWsdlLocation(), ACTIVITYSERVICE_QNAME);
    }

    public ActivityService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ACTIVITYSERVICE_QNAME, features);
    }

    public ActivityService(URL wsdlLocation) {
        super(wsdlLocation, ACTIVITYSERVICE_QNAME);
    }

    public ActivityService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ACTIVITYSERVICE_QNAME, features);
    }

    public ActivityService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ActivityService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ActivityPortType
     */
    @WebEndpoint(name = "ActivityPort")
    public ActivityPortType getActivityPort() {
        return super.getPort(new QName("http://xmlns.oracle.com/Primavera/P6/WS/Activity/V1", "ActivityPort"), ActivityPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ActivityPortType
     */
    @WebEndpoint(name = "ActivityPort")
    public ActivityPortType getActivityPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://xmlns.oracle.com/Primavera/P6/WS/Activity/V1", "ActivityPort"), ActivityPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ACTIVITYSERVICE_EXCEPTION!= null) {
            throw ACTIVITYSERVICE_EXCEPTION;
        }
        return ACTIVITYSERVICE_WSDL_LOCATION;
    }

}
