
package com.wushuo.p6.ActivityPortType;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "IntegrationFault", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/IntegrationFaultType/V1")
public class IntegrationFault
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private IntegrationFaultType faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public IntegrationFault(String message, IntegrationFaultType faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public IntegrationFault(String message, IntegrationFaultType faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.wushuo.p6.ActivityPortType.IntegrationFaultType
     */
    public IntegrationFaultType getFaultInfo() {
        return faultInfo;
    }

}
